<?php

namespace AppBundle\Repository;

/**
 * ApiRestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiRestRepository extends \Doctrine\ORM\EntityRepository
{
}
